param(
    [switch]$CheckOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$LaunchRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$AppRoot = $LaunchRoot
if (Test-Path (Join-Path $LaunchRoot "app\pyproject.toml")) {
    $AppRoot = Join-Path $LaunchRoot "app"
}
$VenvRoot = Join-Path $LaunchRoot ".venv"
$VenvPython = Join-Path $VenvRoot "Scripts\python.exe"
$DiagnosticReport = Join-Path $LaunchRoot "diagnostic_report.txt"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "== $Message =="
}

function Invoke-Python {
    param(
        [string]$PythonCommand,
        [string[]]$Arguments
    )

    if ($PythonCommand -eq "py -3.11") {
        & py -3.11 @Arguments
    } else {
        & $PythonCommand @Arguments
    }
    if ($LASTEXITCODE -ne 0) {
        throw "Python command failed with exit code ${LASTEXITCODE}: $PythonCommand $($Arguments -join ' ')"
    }
}

function Resolve-AuraScript {
    param([string]$RelativePath)

    $rootScript = Join-Path $LaunchRoot $RelativePath
    if (Test-Path $rootScript) {
        return $rootScript
    }
    return Join-Path $AppRoot $RelativePath
}

function Write-DiagnosticReport {
    param(
        [string]$PythonCommand,
        [string]$Status
    )

    $reportScript = Resolve-AuraScript "scripts\runtime_report.py"
    $header = @(
        "Project AURA Diagnostic Report",
        "Generated by Start-AURA.ps1",
        "Status: $Status",
        ""
    ) -join [Environment]::NewLine
    Set-Content -Encoding UTF8 -Path $DiagnosticReport -Value $header

    if ((Test-Path $reportScript) -and $PythonCommand) {
        try {
            Invoke-Python $PythonCommand @($reportScript) 2>&1 | Out-File -Encoding UTF8 -Append $DiagnosticReport
        } catch {
            "runtime_report.py failed: $($_.Exception.Message)" | Out-File -Encoding UTF8 -Append $DiagnosticReport
        }
    } else {
        "runtime_report.py was not available." | Out-File -Encoding UTF8 -Append $DiagnosticReport
    }
}

$ResolvedPython = ""
try {
    Set-Location $AppRoot

    Write-Step "Preparing the locked uv environment"
    if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
        throw "uv was not found. Install uv, then run Start-AURA again."
    }
    $env:UV_PROJECT_ENVIRONMENT = $VenvRoot
    & uv sync --python 3.11 --locked --inexact --extra cli --extra gui --extra capture --extra server --extra punctuation
    if ($LASTEXITCODE -ne 0) {
        throw "uv sync failed with exit code $LASTEXITCODE"
    }
    $ResolvedPython = $VenvPython

    Write-Step "Checking FFmpeg"
    if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
        throw "FFmpeg was not found on PATH. Install FFmpeg or add it to PATH."
    }
    if (-not (Get-Command ffprobe -ErrorAction SilentlyContinue)) {
        throw "ffprobe was not found on PATH. Install FFmpeg or add it to PATH."
    }
    Write-Host "FFmpeg and ffprobe are available."

    Write-Step "Checking NVIDIA driver"
    if (-not (Get-Command nvidia-smi -ErrorAction SilentlyContinue)) {
        throw "nvidia-smi was not found on PATH. Install or update the NVIDIA driver."
    }
    nvidia-smi
    if ($LASTEXITCODE -ne 0) {
        throw "nvidia-smi failed with exit code $LASTEXITCODE."
    }

    Write-Step "Writing diagnostic report"
    Write-DiagnosticReport $ResolvedPython "pre-launch checks"
    Write-Host "Diagnostic report: $DiagnosticReport"

    Write-Step "Checking Windows RTX/CUDA ASR path"
    $gpuSmoke = Resolve-AuraScript "scripts\windows_gpu_smoke.py"
    Invoke-Python $ResolvedPython @($gpuSmoke)

    Write-DiagnosticReport $ResolvedPython "ready"
    if ($CheckOnly) {
        Write-Host ""
        Write-Host "Project AURA runtime checks completed."
        Write-Host "Diagnostic report written to: $DiagnosticReport"
        exit 0
    }

    Write-Step "Starting Project AURA"
    & uv run --no-sync aura gui
    if ($LASTEXITCODE -ne 0) { throw "AURA exited with code $LASTEXITCODE" }
} catch {
    $message = $_.Exception.Message
    Write-Host ""
    Write-Host "Project AURA could not start: $message" -ForegroundColor Red
    try {
        Write-DiagnosticReport $ResolvedPython "failed: $message"
        Write-Host "Diagnostic report written to: $DiagnosticReport"
    } catch {
        Write-Host "Could not write diagnostic report: $($_.Exception.Message)" -ForegroundColor Yellow
    }
    exit 1
}
